package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ArmbandColours generated by hbm2java
 */
public class ArmbandColours  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String value;
     private Set armbandses = new HashSet(0);

    public ArmbandColours() {
    }

    public ArmbandColours(String name, String value, Set armbandses) {
       this.name = name;
       this.value = value;
       this.armbandses = armbandses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getArmbandses() {
        return this.armbandses;
    }
    
    public void setArmbandses(Set armbandses) {
        this.armbandses = armbandses;
    }




}


