package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Armbands generated by hbm2java
 */
public class Armbands  implements java.io.Serializable {


     private Integer id;
     private ArmbandColours armbandColours;
     private Date startDate;
     private Date endDate;
     private String code;
     private Set guestses = new HashSet(0);

    public Armbands() {
    }

	
    public Armbands(ArmbandColours armbandColours, Date startDate, Date endDate, String code) {
        this.armbandColours = armbandColours;
        this.startDate = startDate;
        this.endDate = endDate;
        this.code = code;
    }
    public Armbands(ArmbandColours armbandColours, Date startDate, Date endDate, String code, Set guestses) {
       this.armbandColours = armbandColours;
       this.startDate = startDate;
       this.endDate = endDate;
       this.code = code;
       this.guestses = guestses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ArmbandColours getArmbandColours() {
        return this.armbandColours;
    }
    
    public void setArmbandColours(ArmbandColours armbandColours) {
        this.armbandColours = armbandColours;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getGuestses() {
        return this.guestses;
    }
    
    public void setGuestses(Set guestses) {
        this.guestses = guestses;
    }




}


