package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Drinks generated by hbm2java
 */
public class Drinks  implements java.io.Serializable {


     private Integer id;
     private DrinkTypes drinkTypes;
     private String name;
     private double price;
     private Set orderses = new HashSet(0);

    public Drinks() {
    }

	
    public Drinks(DrinkTypes drinkTypes, String name, double price) {
        this.drinkTypes = drinkTypes;
        this.name = name;
        this.price = price;
    }
    public Drinks(DrinkTypes drinkTypes, String name, double price, Set orderses) {
       this.drinkTypes = drinkTypes;
       this.name = name;
       this.price = price;
       this.orderses = orderses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DrinkTypes getDrinkTypes() {
        return this.drinkTypes;
    }
    
    public void setDrinkTypes(DrinkTypes drinkTypes) {
        this.drinkTypes = drinkTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


