package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Guests generated by hbm2java
 */
public class Guests  implements java.io.Serializable {


     private Integer id;
     private Armbands armbands;
     private String idReal;
     private String name;
     private String password;
     private String code;
     private Set orderses = new HashSet(0);

    public Guests() {
    }

	
    public Guests(Armbands armbands, String name, String code) {
        this.armbands = armbands;
        this.name = name;
        this.code = code;
    }
    public Guests(Armbands armbands, String idReal, String name, String password, String code, Set orderses) {
       this.armbands = armbands;
       this.idReal = idReal;
       this.name = name;
       this.password = password;
       this.code = code;
       this.orderses = orderses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Armbands getArmbands() {
        return this.armbands;
    }
    
    public void setArmbands(Armbands armbands) {
        this.armbands = armbands;
    }
    public String getIdReal() {
        return this.idReal;
    }
    
    public void setIdReal(String idReal) {
        this.idReal = idReal;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


