package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Guests guests;
     private Date date;
     private Set staffs = new HashSet(0);
     private Set drinkses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Guests guests, Date date) {
        this.guests = guests;
        this.date = date;
    }
    public Orders(Guests guests, Date date, Set staffs, Set drinkses) {
       this.guests = guests;
       this.date = date;
       this.staffs = staffs;
       this.drinkses = drinkses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Guests getGuests() {
        return this.guests;
    }
    
    public void setGuests(Guests guests) {
        this.guests = guests;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }
    public Set getDrinkses() {
        return this.drinkses;
    }
    
    public void setDrinkses(Set drinkses) {
        this.drinkses = drinkses;
    }




}


