package hibernate.POJO.classes;
// Generated Mar 24, 2014 1:47:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer id;
     private StaffRoles staffRoles;
     private String idReal;
     private String name;
     private String password;
     private String hours;
     private Set orderses = new HashSet(0);

    public Staff() {
    }

	
    public Staff(StaffRoles staffRoles, String name, String hours) {
        this.staffRoles = staffRoles;
        this.name = name;
        this.hours = hours;
    }
    public Staff(StaffRoles staffRoles, String idReal, String name, String password, String hours, Set orderses) {
       this.staffRoles = staffRoles;
       this.idReal = idReal;
       this.name = name;
       this.password = password;
       this.hours = hours;
       this.orderses = orderses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public StaffRoles getStaffRoles() {
        return this.staffRoles;
    }
    
    public void setStaffRoles(StaffRoles staffRoles) {
        this.staffRoles = staffRoles;
    }
    public String getIdReal() {
        return this.idReal;
    }
    
    public void setIdReal(String idReal) {
        this.idReal = idReal;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHours() {
        return this.hours;
    }
    
    public void setHours(String hours) {
        this.hours = hours;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


